### ISSUE TITLE
searchlight size error

### ISSUE THREAD

**Issue by mike21499** [allefeld/cvmanova#25] opened 2017-04-21 13:51 UTC
Hi Carsten

After loading a dataset
 100 of 365 volumes loaded
  200 of 365 volumes loaded
  300 of 365 volumes loaded
  365 of 365 volumes loaded
 whitening
 high-pass-filtering
 df: 365 - 11 - 10 = 344   [SPM: trRV = 344  erdf = 344]

I get the error : "Error using cvManovaSearchlight (line 67)
data insufficient for searchlight of size 257!"

I've tried different searchlight sizes without success. 

---> if pMax > fEMin * 0.9       % ensures decent numerical precision

seems that the images doesn't meet this criteria....?

thanks and best, mike

**Comment by allefeld** [comment] 2017-04-21 16:32
@mike21499 please specify the exact MATLAB command line with which you started cvManovaSearchlight

**Comment by allefeld** [comment] 2017-04-21 16:35
But I guess the problem is the data. 365 volumes is really a small amount. At a standard TR of 2 seconds, that amounts to 12 minutes. How many sessions are there?

**Comment by mike21499** [comment] 2017-04-22 12:24
HI Carsten
Thanks.
here's an example command: cvManovaSearchlight ('J:\Projects_2\results\1st_level\P20', 4, Cs);
Cs = [1 -1 0 0 0 0 0 0 0]'

Yes, it is only one session and your assumption with the 12min is correct. However, I don't see the point with unsufficient data for a certain searchlight size. In each condition there are 15 samples in randomized order. Is this not sufficient for cross-validation ? 

thanks for help, mike

**Comment by allefeld** [comment] 2017-04-22 16:05
@mike21499 the problem is not the number of trials, but the number of measurements, minus the number of parameters that are estimated, called degrees of freedom. Your data have 344 degrees of freedom, which is not enough to get a decent estimate of the covariance between 257 searchlight voxels. Try searchlight radius 3 = 123 voxels, that should work (but not necessarily well).

This restriction is explained both in the paper and in the README. Since it is not a bug, I'm closing the issue.

**Closed as completed by allefeld** 2017-04-22 16:05 UTC
